apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notify-system
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: notify-system

  source:
    repoURL: git@github.com:bigcrazyfrog/notify.git
    targetRevision: main
    path: k8s
    helm:
      valueFiles:
        - values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
